// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function StartScan(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
