// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProgress():Promise<number>;

export function LogError(arg1:string):Promise<void>;

export function StartScan(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<string>>;

export function StopScan():Promise<void>;
